version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: talentia-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: talentia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - talentia-network

  # Redis (optional, for caching)
  redis:
    image: redis:7-alpine
    container_name: talentia-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - talentia-network

  # Application (for production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talentia-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/talentia
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - talentia-network
    # Uncomment to use external env file
    # env_file:
    #   - .env.local

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  talentia-network:
    driver: bridge

# Development override
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
# For development with hot reload