version: '3.8'

services:
  # Development version of the app with hot reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    container_name: talentia-app-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/talentia
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=dev-secret-key
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
      - redis
    networks:
      - talentia-network
    command: npm run dev

  # PostgreSQL for development
  postgres:
    environment:
      POSTGRES_DB: talentia_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Different port to avoid conflicts